dist: xenial
language: java
addons:
  apt:
    packages:
    - xmlstarlet
  artifacts:
    bucket: dhx-adapter-teststuff
    working_dir: dhx-adapter-integration-tests/target/site/allure-maven-plugin
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - develop
  - master
before_install:
- export TZ=Europe/Helsinki
- xmlstarlet ed -N x="http://maven.apache.org/POM/4.0.0" -d "//x:dependency[x:groupId[contains(text(),'com.oracle')]]" dhx-adapter-server/pom.xml > dhx-adapter-server/pom_without_oracle.xml
- mv dhx-adapter-server/pom_without_oracle.xml dhx-adapter-server/pom.xml
install: true
script:
- mvn clean verify -q
- docker-compose -f dhx-adapter-integration-tests/docker-compose-test.yml down -v
- docker-compose -f dhx-adapter-integration-tests/docker-compose-test.yml build
- docker-compose -f dhx-adapter-integration-tests/docker-compose-test.yml up --exit-code-from setup-wiremock setup-wiremock
- USER_ID=${UID} docker-compose -f dhx-adapter-integration-tests/docker-compose-test.yml up --abort-on-container-exit --exit-code-from test test
- USER_ID=${UID} docker-compose -f dhx-adapter-integration-tests/docker-compose-test.yml up --abort-on-container-exit --exit-code-from report report
after_script:
- docker-compose -f dhx-adapter-integration-tests/docker-compose-test.yml down -v
notifications:
  email:
    recipients:
    - rasmus.soot@nortal.com
    on_success: change
    on_failure: always